### PR TITLE
Add and apply TailwindCSS Typography plugin

### PR DESCRIPTION
**Pull request by podliashanyk**
Relevant for Uninett/Argus#1054

#### Discussion:

- should typography plugin be activated (current implementation) or deactivated on the `<main>` by default?

### CODE REVIEW

**Comment by elfjes** [comment]
What's this about?

**Review by elfjes — CHANGES_REQUESTED** [review]
My initial/gut reaction about using @tailwindcss/typography: Let's be really careful before adding this.

Reading the docs, it seems that the `prose` class is meant for larger sections that have multiple headings, paragraphs, etc (such as content coming from a CMS or rendered markdown). It's called "prose" for a reason. The docs explicitly say that you probably don't want default prose styling, and I agree. The result is that now you need to not-prose large sections of the page, which seems like an antipattern.

If we want to apply some styles to headings because we want a heading system, that is fine, but I'd suggest creating classes for that and not just add style to tags by default.

**Review by lunkwill42 — COMMENTED** [review]
I read your comments about the typography plugin in my PR, but I'm not sure I understand the reasoning, given how the plugin is explained.

We're not about to add large sections of prose to Argus, so I find this a bit overkill just to style some page headings.

**Comment by hmpf** [comment]
should our styles have a prefix? "argus-"?

**Comment by hmpf** [comment]
I'm closing this...

**Pull request closed without merging**
