### PR TITLE
Improve "how to run argus_htmx" in the readme

### PR DESCRIPTION
**Pull request by hmpf**

### CODE REVIEW

**Review by johannaengland — COMMENTED** [review]
For now I can only approve the part using the `Django-style configuration`. That worked great, the only thing that I had to search for, what I would like mentioned in the docs is that one can log in at `accounts/login`, because I tried to go via the Django admin and it would not let me

**Comment by hmpf** [comment]
You should be forced to login if you try to visit `/incidents/` actually. Could you log out and try that?

**Comment by johannaengland** [comment]
> You should be forced to login if you try to visit `/incidents/` actually. Could you log out and try that?

I will get forwarded to `http://localhost:8000/login/?next=/incidents/` and get a `Page not found` error

**Comment by hmpf** [comment]
hah, found it.. new commit on its way.

**Comment by johannaengland** [comment]
Can confirm that this fixes my problem

**Pull request merged**
